# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag', models.ImageField(upload_to=b'/flags')),
            ],
        ),
        migrations.CreateModel(
            name='User_practices_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices_language', to='language.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_speaks_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaks_language', to='language.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaks_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
