# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20160601_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
