# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_language_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_practices_language',
            unique_together=set([('user', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='user_speaks_language',
            unique_together=set([('user', 'language')]),
        ),
    ]
