# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20160601_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=b'flags'),
        ),
    ]
