# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
