# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20160604_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_attends_meeting',
            unique_together=set([('user', 'meeting')]),
        ),
    ]
