# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[(b'MSC', 'Masculine'), (b'FMN', 'Feminine')], max_length=3)),
                ('picture', models.ImageField(upload_to=b'/profiles')),
                ('born_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
