# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='label',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
