# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
    ]
